default_platform(:android)
platform :android do
  desc "Lane for android app destribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --flavor Production --release --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1091436851426:android:e6948573108c7235cd6ebb",
    firebase_cli_token: ENV["TEMPO_FIREBASE_CLI_TOKEN"] ,
    android_artifact_type:"APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers:"mindtech1911@gmail.com",
    release_notes: "Release version #{Time.now.strftime("%Y%m%d%H%M")}"
  )
  end
end